platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'REFrostedViewController', '~> 2.4'
pod 'Unbox'
pod 'RealmSwift'
pod 'PageMenu'
pod 'Firebase', '>= 2.5.0'
pod 'Google/Analytics', '~> 1.0.0'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
pod 'MRProgress'
