platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'REFrostedViewController', '~> 2.4'
pod 'BubbleTransition', '~> 1.0.0'
pod 'ENSwiftSideMenu', '~> 0.1'
pod 'Unbox'
pod 'RealmSwift'
pod 'PageMenu'
pod 'SwiftyUserDefaults'